### ISSUE TITLE
Infografía TypeScript 

### ISSUE THREAD

**Issue by Elisahadad** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Elisahadad#1]
[Infografía TypeScript.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Elisahadad/files/15204822/Infografia.TypeScript.pdf)

**Comment by josealfredo79** [comment]
calificacion.???

**Comment by josealfredo79** [comment]
Bien hecho y revisado
